pipeline {
  agent any
  stages {
    stage('Build') {
      agent any
      environment {
        LOG_LEVEL = 'INFO'
      }
      steps {
        echo "Building release ${RELEASE} with log Level ${LOG_LEVEL}"
      }
    }

    stage('Test') {
      steps {
        echo "Testing. I can see release ${RELEASE}"
      }
    }

    stage('Deploy') {
        input {
          message: 'Deploy?'
          ok 'Do it!'
          parameters {
            string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
          }
        }
        steps {  
        echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
      }
  }
  environment {
    RELEASE = '20.04'
  }
}